"""
Current Controlled Current Source
"""
# Teledyne LeCroy Inc. ("COMPANY") CONFIDENTIAL
# Unpublished Copyright (c) 2015-2016 Peter J. Pupalaikis and Teledyne LeCroy,
# All Rights Reserved.
#
# Explicit license in accompanying README.txt file.  If you don't have that file
# or do not agree to the terms in that file, then you are not licensed to use
# this material whatsoever.

## CurrentControlledCurrentSource
#
# @param G float or complex current gain
#
# @return s-parameter matrix of a current controlled current source
#
# The four port current controlled current source has the current sense element sensing the current
# entering port 1 and exiting port 2 .
# The current generated by the amplifier enters port 4 and exits port 3
# 
def CurrentControlledCurrentSource(G):
    return  [[0.,1.,0.,0.],
            [1.,0.,0.,0.],
            [-G,G,1.,0.],
            [G,-G,0.,1.]]