"""
Current Controlled Voltage Source
"""
# Teledyne LeCroy Inc. ("COMPANY") CONFIDENTIAL
# Unpublished Copyright (c) 2015-2016 Peter J. Pupalaikis and Teledyne LeCroy,
# All Rights Reserved.
#
# Explicit license in accompanying README.txt file.  If you don't have that file
# or do not agree to the terms in that file, then you are not licensed to use
# this material whatsoever.

## CurrentControlledVoltageSource
#
# @param G float or complex transresistance.
# @param Z0 (optional) float or complex reference impedance Z0 (defaults to 50 Ohms).
# @return s-parameter matrix of a current controlled voltage source.
#
# The four port current controlled voltage source has
# the current sense element sensing the current
# entering port 1 and exiting port 2.
#
# The voltage generated by the amplifier has its positive terminal
# at port 4 and its negative terminal at port 3.
def CurrentControlledVoltageSource(G,Z0=50.):
    return  [[0.,1.,0.,0.],
            [1.,0.,0.,0.],
            [-G/(2.*Z0),G/(2.*Z0),0.,1.],
            [G/(2.*Z0),-G/(2.*Z0),1.,0.]]