# Teledyne LeCroy Inc. ("COMPANY") CONFIDENTIAL
# Unpublished Copyright (c) 2015-2016 Peter J. Pupalaikis and Teledyne LeCroy,
# All Rights Reserved.
#
# Explicit license in accompanying README.txt file.  If you don't have that file
# or do not agree to the terms in that file, then you are not licensed to use
# this material whatsoever.

def VoltageControlledCurrentSource(G,Z0=50):
    """AtPackage si.dev.VoltageControlledCurrentSource
    Voltage controlled current source
    @param G float or complex transconductance
    @param Z0 (optional) float or complex reference impedance Z0 (defaults to 50 Ohms)
    @return list of list s-parameter matrix of a voltage controlled current source
    @remarrk
    The four port voltage controlled current source has
    the voltage sense element sensing the voltage difference between the plus terminal
    at port 1 and the minus terminal at port 2.\n
    The current generated by the amplifier enters port 4 and exits port 3
    """
    return  [[1.,0.,0.,0.],
            [0.,1.,0.,0.],
            [2.*G*Z0,-2.*G*Z0,1.,0.],
            [-2.*G*Z0,2.*G*Z0,0.,1.]]