# Teledyne LeCroy Inc. ("COMPANY") CONFIDENTIAL
# Unpublished Copyright (c) 2015-2016 Peter J. Pupalaikis and Teledyne LeCroy,
# All Rights Reserved.
#
# Explicit license in accompanying README.txt file.  If you don't have that file
# or do not agree to the terms in that file, then you are not licensed to use
# this material whatsoever.

def VoltageControlledVoltageSource(G):
    """VoltageControlledVoltageSource
    Voltage controlled voltage source
    @param G float or complex voltage gain
    @return list of list s-parameter matrix of a voltage controlled voltage source
    @remark
    The four port voltage controlled voltage source has
    the voltage sense element sensing the voltage difference between the plus terminal
    at port 1 and the minus terminal at port 2.\n
    The voltage generated by the amplifier has its positive terminal
    at port 4 and its negative terminal at port 3.\n
    """
    return  [[1.,0.,0.,0.],
            [0.,1.,0.,0.],
            [G,-G,0.,1.],
            [-G,G,1.,0.]]